version: '3.8'
services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: super_shiharai_kun
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
